### ISSUE TITLE
Nothing changing in rails admin

### ISSUE THREAD

**Issue by herberzt** [luizpicolo/rails_admin_dropzone#2]
Hey there I'm trying to use this gem in my rails project and not having much luck. 

Here is a quick background of my different models that I'm trying to integrate you example with.

Class Item: ``has_many images`` (assuming this would be album)
Class Image
Class ItemImage < Image: ``belongs_to item`` (assuming this would be photo)

In item.rb I added the following like in your example:
```
def create_associated_image(image)
    images.create(image: image)
end
```

in my ``rails_admin.rb`` I added:
```
dropzone do
  only Image
end
```

Is there anything i have missed or any other stuff that I need to do?

**Comment by luizpicolo** [comment]
Hello @herberzt, who do you do?
Plz, post your code in https://gist.github.com/ that i help you.

Best, Luiz

**Comment by ckk-scratch** [comment]
Hey @luizpicolo - Really cool extension - but also dealing with nothing happening after install & config. Looked at your 1.0 vsn to see if I missed a generator or something, but attaching some gists of my setup here. Nothing is registering in my Rails Admin page. Will try to fork and dig in locally if still not working. 

https://gist.github.com/ckk-scratch/ebca69b2dea368e7fbad1cad505d5cff

**Comment by luizpicolo** [comment]
Hello @ckk-scratch 

You are using version 1.0.0?

**Comment by ckk-scratch** [comment]
@luizpicolo - Nope I am using rails_admin_dropzone (1.0.7)

**Comment by luizpicolo** [comment]
Hey @ckk-scratch your field image se called "hero" or "image":

```ruby
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
	has_and_belongs_to_many :artists
	has_many :gallery_images
	belongs_to :category

	has_attached_file :hero, styles: { large: "1280x1024>", medium: "650x650" }
  validates_attachment_content_type :hero, content_type: /\Aimage\/.*\Z/

  # Method
  def create_associated_image(image)
    gallery_images.create(image: image)
  end

end
```

Try changing attribute "hero" to "image", This worked for me

```ruby
class GalleryImage < ActiveRecord::Base
  attr_accessor :image, :project_id, :image_file_name

  has_attached_file :image, :styles => { :thumb => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :project
end
```

**Comment by ckk-scratch** [comment]
But isn't this  supposed to relate to the attachment name in the associated bulk uploaded GalleryImage, which name is **image**?

Ahh however I actually just realized its not meant to be appended to the traditional edit, but its own area.
 
<img width="273" alt="screen shot 2016-08-02 at 2 32 42 pm" src="https://cloud.githubusercontent.com/assets/12697056/17340493/56a1f810-58be-11e6-8060-2de5e89dadad.png">

However, I am now receive a missing template error.  _Will attach the error_ I will work with this now that I got it to show up and only re-open an issue or commit a PR if I figure out what happened on my initialization. 

`Started POST "/studio/project/5/dropzone" for ::1 at 2016-08-02 14:33:47 -0400
Processing by RailsAdmin::MainController#dropzone as JSON
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"PhT0l1x+680pCsUOrLR/P4/VtH7dwTBqC9l2iJBFLDFFUfbpUGfn+lW9oRFFmtiJoFBSOZQR8V0WMFFKt9xaHw==", "id"=>"5", "file"=>#<ActionDispatch::Http::UploadedFile:0x007f95609a7b88 @tempfile=#<Tempfile:/var/folders/ty/jzsrz66j6f7_hw0fwmbdhk2m0000gn/T/RackMultipart20160802-5740-j5bczj.png>, @original_filename="Screen Shot 2016-07-26 at 4.34.45 PM.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"Screen Shot 2016-07-26 at 4.34.45 PM.png\"\r\nContent-Type: image/png\r\n">, "model_name"=>"project"}
  Project Load (0.3ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = $1  ORDER BY "projects"."id" ASC LIMIT 1  [["id", 5]]
  Project Load (0.4ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT 1  [["id", 5]]
Completed 500 Internal Server Error in 29ms (ActiveRecord: 0.7ms)

ActionView::MissingTemplate - Missing template rails_admin/main/dropzone, rails_admin/application/dropzone, application/dropzone with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml, :jbuilder]}. Searched in:
  * "/Users/SerKnight/Desktop/projects/scratch/artolution/solution/app/views"
  * "/Users/SerKnight/.rvm/gems/ruby-2.2.2@solution/gems/rails_admin_dropzone-1.0.7/app/views"
  * "/Users/SerKnight/.rvm/gems/ruby-2.2.2@solution/gems/devise-3.5.6/app/views"
  * "/Users/SerKnight/.rvm/gems/ruby-2.2.2@solution/gems/rails_admin-0.8.1/app/views"
  * "/Users/SerKnight/.rvm/gems/ruby-2.2.2@solution/gems/kaminari-0.16.3/app/views"
`

**Comment by luizpicolo** [comment]
Example

[dropzone_paperclip.tar.gz](https://github.com/luizpicolo/rails_admin_dropzone/files/397896/dropzone_paperclip.tar.gz)

**Comment by ckk-scratch** [comment]
Awesome - Thanks a lot Luiz
