### ISSUE TITLE
Missing template rails_admin/main/dropzone

### ISSUE THREAD

**Issue by wraithseeker** [luizpicolo/rails_admin_dropzone#3]
Nothing visible can be seen on rails_admin, even though I have followed the instructions on the README.

`
Missing template rails_admin/main/dropzone, rails_admin/application/dropzone, application/dropzone with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml]}`

```
class ProductImage < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, DefaultUploader
end

class Product < ActiveRecord::Base
	has_many :product_images

  	def create_associated_image(image)
    	product_images.create(image: image)
  	end
end
```

```
RailsAdmin.config do |config|
config.actions do
    dashboard                  
    index                        
    new
    dropzone do
      only Product # Example Album
    end
    export
    bulk_delete
    show
    edit
    delete
    show_in_app
  end
end
```

**Comment by wraithseeker** [comment]
EDIT: I found out that I had to create the product first to locate the dropzone action. Now I have another problem when uploading the image and this error is shown.

**Comment by luizpicolo** [comment]
Hello @wraithseeker 

I added an example in repository. Check files:

 - Gemfile
 - model/album.rb
 - model/photo.rb
 - config/initialize/rails_admin.rb

Best.

**Comment by wraithseeker** [comment]
Thanks for taking time out to set an example project @luizpicolo, I started the example repository and it worked for me at so after that I did the same thing in my rails project and it worked too. 

However, when I create a model named 'Product' and 'ProductImages', I still receive the same error on both my rails project and also when I try to set it up on the example repo.

 Could the model names be hardcoded or am I missing something?

**Comment by luizpicolo** [comment]
Hello @wraithseeker, thanks for replay
Really. I will implement a way to remedy this problem. I was not thinking about it.

**Comment by luizpicolo** [comment]
Heyt @wraithseeker.

Fixed the problem. It was not the best solution, however, solves our problem :smile:

**Comment by luizpicolo** [comment]
Hey @wraithseeker.
I fixed the problem. It was not the best, but is working properly. :smile: 
Check new version v1.0.7
