### ISSUE TITLE
Error if model has _

### ISSUE THREAD

**Issue by RocKhalil** [luizpicolo/rails_admin_dropzone#39]
For example, if you have a model `LocationAlbum` then the param key will be `locationalbum` while the `@abstract_model.param_key` will return `location_album`.

To fix it:
`@params = params[@abstract_model.param_key.gsub('_', '')]`

**Comment by mskcodes** [comment]
Can you give me patch code for pull request? I also found same bug.

**Comment by RocKhalil** [comment]
@mskcodes this was reported 2 years ago and unfortunately we've changed a lot since in the code then. I'm not sure if this is still working. You have to monkey-patch it:

```
module RailsAdmin
  module Config
    module Actions
      class Dropzone < Base
        RailsAdmin::Config::Actions.register(self)
        register_instance_option :member do
          true
        end

        register_instance_option :link_icon do
          'icon-upload'
        end

        register_instance_option :http_methods do
          [:get, :post]
        end

        register_instance_option :controller do
          Proc.new do
            @response = {}

            if request.post?
              @object = @abstract_model.model.find(params[:id])
              @params = params[@abstract_model.param_key.gsub('_', '')]

              if @params.present?
                @params[:second_attr].each do |image|
                  if @object.create_associated_image(image)
                    render json: { message: 'success', fileID: '1' }, status: 200
                  else
                    render json: { error: @object.dropzone_association.errors.full_messages.join(',')}, status: 400
                  end
                end
              end
            end
          end
        end
      end
    end
  end
end
```

**Comment by mskcodes** [comment]
Thanks I did @RocKhalil your patch code work well below versions.

ruby 2.5.1 
rails 4.2.11.3
gem 'rails_admin', '1.4.3'
gem 'rails_admin_dropzone', '1.0.8'

but, I think This code need will apply override on RailsAdmin::MainController#dropzone right? 

Can you make pull request? if original author @luizpicolo No answer, you can fork and patch directly.

**Comment by RocKhalil** [comment]
@mskcodes correct. I think the repo is no longer maintained is not being used a lot. Feel free to do the PR yourself :-)

**Comment by luizpicolo** [comment]
Hello guys, I created this gem but it hasn't been used for a long time. However, if you prefer to send a PR I will have the pleasure of reviewing and doing the Merge

Best regards

**Comment by mskcodes** [comment]
I also find fix only that line code later can be uploaded.

```javascript
diff --git a/app/views/rails_admin/main/dropzone.html.haml b/app/views/rails_admin/main/dropzone.html.haml
index d0004aa..187303f 100644
--- a/app/views/rails_admin/main/dropzone.html.haml
+++ b/app/views/rails_admin/main/dropzone.html.haml
@@ -8,7 +8,7 @@
     if ($(".dropzone").length){
       var dropzone = new Dropzone (".dropzone", {
         maxFilesize: 256, // Set the maximum file size to 256 MB
-        paramName: "#{@object.class.to_s.downcase}[second_attr][]", // Rails expects the file upload to be something like model[field_name]
+        paramName: "#{@object.model_name.param_key}[second_attr][]", // Rails expects the file upload to be something like model[field_name]
         addRemoveLinks: false, // Don't show remove links on dropzone itself.
         // Translations
         dictDefaultMessage: "#{I18n.t('admin.actions.dropzone.dictDefaultMessage')}",
```

**Comment by luizpicolo** [comment]
Hello guys. i added support for rails version 6. Fixed some bugs and updated a new version in RubyGems. For support rails < 6 i recommend the version 1.0.8. Above i recommend the last version.

i'm waiting now yours PRs. 

best regards
Picolo
