### ISSUE TITLE
Add new translations

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/rails_admin_dropzone#5]
Today the system has only 3 language. It is interesting to add new translations. Happy translations!

**Comment by dosten** [comment]
I can add a spanish translation, I only need to create a new `config/locales/multiple_upload.es.yml` file? or I need to touch other files?

**Comment by pish4** [comment]
I can add ukrainian translation if you are interested.

**Comment by luizpicolo** [comment]
Hello @dosten. Yes, add a new file in `config/locales/` with name `multiple_upload.es.yml` and happy translation. :smile:

**Comment by luizpicolo** [comment]
@pish4 welcome :+1:

**Comment by I-am-me** [comment]
I'll be doing French translation

**Comment by divayprakash** [comment]
Doing translation for Hindi and German!

**Comment by dosten** [comment]
@luizpicolo I think that you must reopen this issue as some people (like me) search for **open issues** with the label hacktoberfest

**Comment by luizpicolo** [comment]
Sorry @dosten, reopened

**Comment by Lyxnx** [comment]
Currently working on a Norwegian translation if you would like it

**Comment by dosten** [comment]
@luizpicolo If a PR says "fixes #X" when the PR is merged the issue #X is closed automatically.

**Comment by luizpicolo** [comment]
@dosten okay, now understood

**Comment by luizpicolo** [comment]
@Lyxnx wolcome and go ahead.

**Comment by AndreeaEne** [comment]
Romanian translation coming.

**Comment by luizpicolo** [comment]
@AndreeaEne :tada:

**Comment by AndreeaEne** [comment]
Danish translation, too 🇩🇰!

**Comment by wahbigbig** [comment]
working on Traditional Chinese

**Comment by luizpicolo** [comment]
@wahbigbig :cn:  is :tada:

**Comment by ivanorsolic** [comment]
Working on the Croatian translation

**Comment by nemfoz** [comment]
I could do the greek translation if it's ok!

**Comment by bSzala** [comment]
I can do a Polish translation

**Comment by luizpicolo** [comment]
hey @bSzala, check your PR #23

**Comment by Robiathin** [comment]
:sweden:  Added Swedish translations in pull request #25

**Comment by rodsei** [comment]
I can do a Portuguese translation

**Comment by wahbigbig** [comment]
Traditional Chinese is for Hong Kong/Taiwan
China use Simplified Chinese

**Comment by domcorvasce** [comment]
Can I add an italian translation?

**Comment by luizpicolo** [comment]
You only not can, you should :)

**Comment by justthegame** [comment]
I'll add Indonesian.
